fos_rest:
    service:
        templating: null # deprecated warning
    serializer:
        serialize_null: true
    view:
        default_engine: null # deprecated warning
        force_redirects: [] # deprecated warning
        view_response_listener:  true
        failed_validation: 422
    body_listener:
        array_normalizer:
            service: App\Serializer\Normalizer\SymfonyCamelKeysNormalizer
            forms: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, xml ] }
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }
