fos_rest:
    serializer:
        serialize_null: true
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/v1, prefer_extension: true, fallback_format: json, priorities: [ json, xml ] }
            - { path: ^/,   prefer_extension: true, fallback_format: html }
