security:
    encoders:
        App\Entity\User: { algorithm: auto }

    providers:
        entity_provider:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # refresh_token:
        #     pattern: ^/auth/refresh_token
        #     stateless: true
        #     anonymous: lazy
        #     guard:
        #         authenticators:
        #             - App\Security\JWTRefreshTokenAuthenticator

        token:
            pattern: ^/auth/token
            stateless: true
            anonymous: lazy
            json_login:
                check_path: /auth/token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern: ^/
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/auth/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,           roles: IS_AUTHENTICATED_FULLY }
