security:

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

        app_user_token_provider:
            entity:
                class: App\Entity\UserToken
                property: refreshToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh_token:
            pattern: ^/refresh_token
            stateless: true
            anonymous: lazy
            provider: app_user_token_provider
            guard:
                authenticators:
                    - App\Security\Authenticator\RefreshTokenAuthenticator

        token:
            pattern: ^/token
            stateless: true
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\Authenticator\UsernamePasswordAuthenticator

        main:
            pattern: ^/
            stateless: true
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\Authenticator\TokenAuthenticator

    access_control:
        - { path: ^/public_area,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/token,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,               roles: IS_AUTHENTICATED_FULLY }
