security:

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_token_post:
            pattern: ^/api/token
            methods: POST
            stateless: true
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\Authenticator\UsernamePasswordAuthenticator

        api_token_put:
            pattern: ^/api/token
            methods: PUT
            stateless: true
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\Authenticator\RefreshTokenAuthenticator

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\Authenticator\JWTAuthenticator

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
