security:

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh_token:
            pattern: ^/v1/refresh_token
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\RefreshTokenAuthenticator

        access_token:
            pattern: ^/v1/access_token
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\AccessTokenAuthenticator

        main:
            pattern: ^/v1
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\ApiAuthenticator

    access_control:
        - { path: ^/v1/public_area,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1,                 roles: IS_AUTHENTICATED_FULLY }
