security:

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh_token:
            pattern: ^/api/refresh_token
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\RefreshTokenAuthenticator

        token:
            pattern: ^/api/token
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\UsernamePasswordAuthenticator

        main:
            pattern: ^/api
            stateless: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Authenticator\JWTAuthenticator

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
