controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

API:
    resource: ../../src/Controller/API
    prefix: /api
    type: annotation
